# -*- coding: utf-8 -*-
"""Copy of Calcula_area_triang_circ

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PMD8p37idKcLbDX33SdjaBRf4XO3_7BQ
"""

#this program helps to achive the area of a shape

print('You can calculate, now!')
shape = input ('tell me what kinda shape do you want to calculate the area? ')

if shape == 'C':
  print ('Ok, you wanna a circle!')
  radius = float(input ('give the radius, please: '))
  area = 3.14159 * radius**2
  print ('The area is %s.', area)
elif shape == 'T':
	#print ('Ok, you wanna a triangle!')
  base = float(input('Enter the base of the triangle, please: '))
  height = float(input('Enter the height of the triangle, please: '))
  area = (base * height)/2
  print ('The area is %s.',area)
else:
  print ('Error 404: not found')
print ('The program is exiting! Thank you, come agaain!')